config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  
    

  root "home#index"

  resources :notes
  resources :members do

  end

end

app/models/member.rb
class Member < ActiveRecord::Base
  has_many :notes
  
end

app/models/note.rb
class Note < ActiveRecord::Base
  HUMANIZED_ATTRIBUTES = {
    :note_tag_id => "Type"
  }
  scope :today_by_user, ->(uid) { where("created_at::date = current_date and user_id = ?", uid) }
  scope :reverse, -> { order(id:'desc') } 
  belongs_to :tag, :class_name=>'Note::Tag', :foreign_key => "note_tag_id"
  validates_presence_of :member_id, :note_tag_id, :note
  
  # delegate :tag to: :note_tag
  
  belongs_to :user
  
  belongs_to :member
  # delegate :name to: :member

  # Give us human attribute name instead of column name
  def self.human_attribute_name(attr,options={})
    HUMANIZED_ATTRIBUTES[attr.to_sym] || super
  end

end

app/models/note/tag.rb
class Note::Tag < ActiveRecord::Base
  has_many :notes, :foreign_key => "note_tag_id", :primary_key => "id", :class_name => "::Note"
    
  def tag
    self.name
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :notes
         
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index
    
  end

end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: [:show, :edit, :update, :destroy]

  # GET /members
  def index
    @members = Member.all
  end

  # GET /members/1
  def show
  end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members
  def create
    @member = Member.new(member_params)

    if @member.save
      redirect_to members_path, notice: "#{@member.name} successfully added." and return
    else
      render :new
    end
  end

  # PATCH/PUT /members/1
  def update
    if @member.update(member_params)
      redirect_to members_path, notice:  "#{@member.name} successfully updated." and return
    else
      render :edit
    end
  end

  # DELETE /members/1
  def destroy
    @member.destroy
    redirect_to members_url, notice: 'Member was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def member_params
      params.require(:member).permit(:name, :email)
    end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]

  # GET /notes
  def index
    @notes = Note.all.reverse
  end

  # GET /notes/1
  def show
  end

  # GET /notes/new
  def new
    @note = Note.new
    @current = Note.today_by_user(current_user.id).reverse
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes
  def create
    note = Note.new(note_params)
    note.user_id = current_user.id
    if note.save
      @note = note.dup
      @note.note = nil # nill out the note part
      @current = Note.today_by_user(current_user.id).reverse
      render :new 
# want rapid-fire note-taking, so we just update and move on
      # redirect_to notes_path, notice:  "#{@member.name} successfully updated." and return
    else
      @note = note
      render :new
    end
  end

  # PATCH/PUT /notes/1
  def update
    if @note.update(note_params)
      redirect_to notes_path, notice:  "#{@note.member.name} note successfully updated." and return
    else
      render :edit
    end
  end

  # DELETE /notes/1
  def destroy
    @note.destroy
    redirect_to notes_url, notice: 'Note was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def note_params
      params.require(:note).permit(:member_id, :note_tag_id, :note)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def nav_bar_current?(page)
    select = (@nav_here.present?) ? @nav_here : request.fullpath.split("?")[0]
    page == select ? 'active' : ''
  end
end

app/helpers/devise_helper.rb
# From : https://github.com/plataformatec/devise/wiki/Override-devise_error_messages!-for-views
# modified ala : http://stackoverflow.com/questions/18780752/rails-render-partial-in-helper
module DeviseHelper
  def devise_error_messages!(message:nil,emphasis:nil)
    return "" if resource.errors.empty?

    if message.nil?
      li = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join.html_safe
      message = content_tag(:ul,li)
    end
    
    if emphasis.nil?
      emphasis = I18n.t("errors.messages.not_saved",
                      :count => resource.errors.count,
                      :resource => resource.class.model_name.human.downcase) 
    end
    html = render partial: '/partials/dismissable_alert', locals:{klass:'danger',emphasis:emphasis,message:message}
    html.html_safe
  end

  def devise_error_messages?
    resource.errors.empty? ? false : true
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/notes_helper.rb
module NotesHelper

  def labelize(str)
    klass = 'default'
    case str
    when 'action_item'
      klass = 'primary'
    when 'question'
      klass = 'warning'
    when 'concern'
      klass = 'danger'
    when 'goal'
      klass = 'success'
    end
    content_tag(:button, str.humanize.titleize, class:"btn btn-#{klass} btn-xs")
  end
end

app/views/home/index.html.haml
%p.lead
  Not much to see here.  To get started you might want to 

= link_to('Add a Note', new_note_path, class:"btn btn-primary btn-lg")
  

app/views/layouts/application.html.haml
!!!5
%head
  %title recap
  = stylesheet_link_tag    'application', media: 'all'
  = javascript_include_tag 'application'
  = csrf_meta_tags

%body
  -# Navbar
  %nav.navbar.navbar-default.navbar-fixed-top
    .container-fluid
      .navbar-header
        %button.navbar-toggle.collapsed{type:"button",data:{toggle:"collapse",target:"#navbar-collapse"}}
          %span.sr-only Toggle navigation
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.navbar-brand{href:root_path} recap

      - if user_signed_in?
        .collapse.navbar-collapse{id:"navbar-collapse"}
          %ul.nav.navbar-nav
            %li{:class => nav_bar_current?(notes_path)}
              =link_to 'Notes', notes_path
            %li{:class => nav_bar_current?(members_path)} 
              =link_to 'Members', members_path
            -#%li 
              %a{href:'#'} Contact
            
          %ul.nav.navbar-nav.navbar-right
            %li.dropdown
              %a.dropdown-toggle{href:'#',data:{toggle:'dropdown'},role:'button'} 
                #{current_user.email}
                %span.caret
              %ul.dropdown-menu{role:'menu'}
                %li
                  =link_to('Account',edit_user_registration_path())
                %li.divider
                %li
                  =link_to('Logout',destroy_user_session_path(),data:{method:'delete'},rel:'nofollow')

  -# Primary content area
  .container-fluid
    .row
      -# Side-Nav box
      -#.col-xs-3.col-md-2
        .well.sidebar-nav
          %ul.nav.nav-list
            %li.nav-header Sidebar
            %li.active Link 1
            %li Link 2
            %li.nav-header Sidebar2 
            %li Link 3
            %li Link 4
            %li Link 5
          </ul>
      -# Primary content screen
      .col-md-10.col-md-offset-1
        = yield

app/views/members/_form.html.erb
<%= form_for(@member) do |f| %>
  <% if @member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
      <% @member.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/members/edit.html.erb
<%- @nav_here = members_path %>
<h1>Editing Member</h1>

<%= render '/members/partials/base' %>

<%= link_to 'Show', @member %> |
<%= link_to 'Back', members_path %>

app/views/members/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Members</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @members.each do |member| %>
      <tr>
        <td><%= member.name %></td>
        <td><%= member.email %></td>
        <td><%= link_to 'Show', member %></td>
        <td><%= link_to 'Edit', edit_member_path(member) %></td>
        <!--<td><%= link_to 'Destroy', member, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
        <td><%= link_to 'New Note', edit_member_path(member) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Member', new_member_path %>

app/views/members/index.html.haml
= render '/partials/notice'

%h1 Members

= render partial: '/members/partials/set', locals:{set:@members}

=link_to( 'New Member', new_member_path, {class:'btn btn-primary btn-lg', role:'button'})

app/views/members/new.html.erb
<%- @nav_here = members_path %>
<h1>New Member</h1>

<%= render '/members/partials/base' %>

<%= link_to 'Back', members_path %>

app/views/members/partials/_base.html.haml
= form_for(@member, html: {class:'form-inline'}) do |f|
  - if @member.errors.any? 
    = render '/partials/standard_form_errors', locals: {errors: @member.errors}

  .form-group
    = f.label :name, class:'sr-only'
    = f.text_field :name, class:'form-control', placeholder:'Member Name'

  .form-group
    = f.label :email, class:'sr-only'
    = f.text_field :email, class:'form-control', placeholder:'Email Address'

  %button.btn.btn-info{type:'submit'} Submit

app/views/members/partials/_list.html.haml
- member ||= nil
- if member.present?
  %tr
    %td= member.name
    %td= member.email
    %td= member.notes.count
    %td
      - if member.id # we might want to change this to members over whom I have edit capabilities
        %a{href:edit_member_path(member), title:'Edit'}
          %span.glyphicon.glyphicon-pencil{"aria-hidden"=>true}
        &nbsp;
        -#%a{href:note_path(note), data: { confirm: 'Are you sure?', method: 'delete' }, rel:'nofollow', title:'Delete'}
          %span.glyphicon.glyphicon-trash{"aria-hidden"=>true}
      - else
        &nbsp;

app/views/members/partials/_set.html.haml
- set ||= []
- if set.present?
  %table.table.table-striped{id:'member-list'}
    %thead
      %tr
        %th Name
        %th Email
        %th Notes
        %th

    %tbody
      - set.each do |member|
        = render partial: '/members/partials/list', locals:{member:member}

app/views/members/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @member.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @member.email %>
</p>

<%= link_to 'Edit', edit_member_path(@member) %> |
<%= link_to 'Back', members_path %>

app/views/notes/edit.html.erb
<h1>Editing Note</h1>

<%= render '/notes/partials/base' %>

<%= link_to 'Show', @note %> |
<%= link_to 'Back', notes_path %>

app/views/notes/index.html.haml
= render '/partials/notice'

%h1 Notes

= render partial: '/notes/partials/set', locals:{set:@notes}

=link_to( 'New Note', new_note_path, {class:'btn btn-primary btn-lg', role:'button'})

app/views/notes/new.html.erb
<h1>New Note</h1>

<%= render '/notes/partials/base' %>


<%= link_to 'Back', notes_path %>

app/views/notes/new.html.haml
- @nav_here = notes_path

%h1 Add a Note

= render '/notes/partials/base'

%br

= render partial: '/notes/partials/current', locals:{set:@current}

app/views/notes/partials/_base.html.haml
= form_for(@note, html: {class:'form-inline'}) do |f|
  - if @note.errors.any? 
    = render partial: '/partials/standard_form_errors', locals: {errors: @note.errors}

  .form-group
    = f.label :member_id, class:'sr-only'
    = f.select(:member_id, Member.all.collect {|p| [ p.name, p.id ] }, { include_blank: false, prompt:'Member' }, class:'input-lg')

  .form-group
    = f.label :note_tag_id, class:'sr-only'
    = f.select(:note_tag_id, Note::Tag.all.collect {|p| [ p.name.humanize.titleize, p.id ] }, { include_blank: false, prompt:'Type' }, class:'input-lg')

  .form-group
    = f.label :note, class:'sr-only'
    = f.text_field :note, class:'form-control input-lg', style:'width:700px;', placeholder:'Note', autofocus: true 

  %button.btn.btn-primary.btn-lg{type:'submit'} 
    %span.glyphicon.glyphicon-plus
    Add

app/views/notes/partials/_current.html.haml
- set ||= []
- if set.present?
  .panel.panel-info
    .panel-heading Today's Notes
    = render partial: '/notes/partials/set', locals:{set:set}
  

app/views/notes/partials/_list.html.haml
- note ||= nil
- if note.present?
  %tr
    %td= note.member.name
    %td= labelize(note.tag.name)
    %td= note.note
    %td
      - if note.user_id == current_user.id
        %a{href:edit_note_path(note), title:'Edit'}
          %span.glyphicon.glyphicon-pencil{"aria-hidden"=>true}
        &nbsp;
        %a{href:note_path(note), data: { confirm: 'Are you sure?', method: 'delete' }, rel:'nofollow', title:'Delete'}
          %span.glyphicon.glyphicon-trash{"aria-hidden"=>true}
      - else
        &nbsp;
  
  

app/views/notes/partials/_set.html.haml
- set ||= []
- if set.present?
  %table.table.table-striped{id:'note-list'}
    %thead
      %tr
        %th Member
        %th Tag
        %th Note
        %th

    %tbody
      - set.each do |note|
        = render partial: '/notes/partials/list', locals:{note:note}

app/views/notes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Member:</strong>
  <%= @note.member.name %>
</p>

<p>
  <strong>Note tag:</strong>
  <%= @note.tag.name %>
</p>

<p>
  <strong>Note:</strong>
  <%= @note.note %>
</p>

<%= link_to 'Edit', edit_note_path(@note) %> |
<%= link_to 'Back', notes_path %>

app/views/partials/_dismissable_alert.html.haml
- klass ||= nil
- emphasis ||= nil
- message ||= nil

- if klass.present? && message.present?
  .alert{class:"alert-#{klass}"}
    =link_to(raw('&times;'),'#', {class:'close',data:{dismiss:'alert'}})
    - if emphasis
      %strong 
        = emphasis
    = message

app/views/partials/_notice.html.haml
- if notice
  = render partial: '/partials/dismissable_alert', locals:{klass:'success',emphasis:'Success!',message:notice}
- if alert
  = render partial: '/partials/dismissable_alert', locals:{klass:'danger',emphasis:'Error!',message:alert}

app/views/partials/_standard_form_errors.html.haml
- errors ||= []
- if errors.count > 0
  - emp = "#{pluralize(errors.count, 'error')} found:"
  - msg = capture_haml do
    %ul
      - errors.full_messages.each do |err|
        %li= err

  = render partial: '/partials/dismissable_alert', locals:{klass:'danger',emphasis:emp,message:msg}